### ISSUE TITLE
CentOS7下运行报错

### ISSUE THREAD

**Issue by Chas-IO** [mixool/HiCnUnicom#1]
正确的账号密码，提示登录失败。sh -x CnUnicom.sh 提示如下错误。
CnUnicom.sh: command substitution: line 42: syntax error near unexpected token `('
CnUnicom.sh: command substitution: line 42: `echo -n $username | openssl rsautl -encrypt -inkey $workdir/rsa_public.key -pubin -out >(base64 | tr "\n" " " | sed s/[[:space:]]//g))'

**Comment by hzys** [comment]
> 正确的账号密码，提示登录失败。sh -x CnUnicom.sh 提示如下错误。
> CnUnicom.sh: command substitution: line 42: syntax error near unexpected token `(' CnUnicom.sh: command substitution: line 42: `echo -n $username | openssl rsautl -encrypt -inkey $workdir/rsa_public.key -pubin -out >(base64 | tr "\n" " " | sed s/[[:space:]]//g))'

看代码56行，你要自己抓包appid

**Comment by mixool** [comment]
`bash <(curl -s https://raw.githubusercontent.com/mixool/HiCnUnicom/master/CnUnicom.sh) ${username} ${password}`
如上运行一次 不报代码错误的话 说明你自己修改的格式有问题，另外
> 看代码56行，你要自己抓包appid

**Comment by Chas-IO** [comment]
# sh CnUnicom.sh ${username} ${password}
CnUnicom.sh: command substitution: line 42: syntax error near unexpected token `('
CnUnicom.sh: command substitution: line 42: `echo -n $username | openssl rsautl -encrypt -inkey $workdir/rsa_public.key -pubin -out >(base64 | tr "\n" " " | sed s/[[:space:]]//g))'

一样错误。

**Comment by mixool** [comment]
@Chas-IO 代码在debian 9 和 10 下测试没问题 ，建议在新机器上测试下

**Comment by Chas-IO** [comment]
能不能增加下不同unix发行版本下的适配性。
