### ISSUE TITLE
多手机号多流量领取方式

### ISSUE THREAD

**Issue by fys666** [mixool/HiCnUnicom#14]
你好，可以更新一下多手机号的领取方式吗？比如1手机号每月2日开通1G流量，2手机号不仅每月2日开通1G流量，还可以开通4GB流量七日包，实现多手机号多种流量领取方式的功能。
麻烦了，祝新年快乐

**Comment by mixool** [comment]
目前多参数运行几次就行了

**Comment by fys666** [comment]
![AO7{QOXBODWWZWK9GVO91Z3](https://user-images.githubusercontent.com/55824187/107042956-4e1f6800-67fd-11eb-958c-f67c6932ddb7.jpg)

好滴，谢谢，又来打扰了，更新以后这个流量不再领取了，打扰了

**Comment by mixool** [comment]
sh的说明里面asm流量积分多，建议去用那个

**Comment by fys666** [comment]
> sh的说明里面asm流量积分多，建议去用那个

哥，我找了半天也没有asm这个关键词，你是说membercenter这个函数吗？
我已经进行了类似的添加membercenter 12345678901@112233
实在是不知道了
谢谢

**Comment by mixool** [comment]
sh的使用教程readme里面，第四个
