### ISSUE TITLE
Ac运行出错 请问是哪里的问题

### ISSUE THREAD

**Issue by a327777892** [mixool/HiCnUnicom#15]
签到: .github#L1
Process completed with exit code 1.
签到: .github#L1
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by mixool** [comment]
支持AC的是这个： https://github.com/hzys/HiCnUnicom
可以去那里提Issues
