### ISSUE TITLE
关于安卓termux有问

### ISSUE THREAD

**Issue by q7871177xhj** [mixool/HiCnUnicom#19]
你好 想问下安卓termux应该可以运行使用CnUnicom.sh吧 但我不知道需要安装哪些环境依赖 运行一直报错 相对于放github上 本地版感觉更方便修改和添加参数 对github不熟练

**Comment by mixool** [comment]
脚本只在vps上进行了测试，我也不熟悉termux

**Comment by q7871177xhj** [comment]
> 脚本只在vps上进行了测试，我也不熟悉termux

已经弄好了 用的别人提供的pm2搭建环境 然后修改路径后可以执行了 谢谢你的脚本
