### ISSUE TITLE
无法激活每日领取的1g流量日包(就是我的礼包里 做任务领奖品的1g日包)

### ISSUE THREAD

**Issue by q7871177xhj** [mixool/HiCnUnicom#37]
导入参数liulactive@w@null@13800008888-13012341234@mygiftbag 无法激活每日领取的1g流量包 想问问是不是我导入错误了
尝试了好几个参数 能激活成功的还是以前的流量包代码的 而每日领取的1g流量包激活没提示 也没成功

**Comment by q7871177xhj** [comment]
![QQ图片20210321162123](https://user-images.githubusercontent.com/76708409/111898516-82737e80-8a61-11eb-9995-3525723b13d0.jpg)
![QQ图片20210321162126](https://user-images.githubusercontent.com/76708409/111898519-87d0c900-8a61-11eb-9823-fd1626435e64.jpg)
一个是流量包代码的激活流量 能够正常激活
一个是每日1g日包的激活流量 无法激活 也不提示别的信息

不知道是不是我理解错参数的导入方法了

**Comment by q7871177xhj** [comment]
liulactive@m@null@13012341234@mygiftbag 这个参数也试过

**Comment by q7871177xhj** [comment]
直接liulactive@d@mygiftbag 会提示激活失败 但手动去app里又能激活成功

**Comment by mixool** [comment]
liulactive@d@null@13012341234@mygiftbag


d 才表示每天

**Comment by q7871177xhj** [comment]
> liulactive @ d @ null @ 13012341234 @ mygiftbag
> 
> d才表示每天
用了 把能用的组合都试了 激活我的礼包的日流量就没反应 本来截图了 我重新打码下吧
![Uploading QQ图片20210321233028.png…]()
![Uploading QQ图片20210321233033.jpg…]()

**Comment by q7871177xhj** [comment]
![QQ图片20210321233028](https://user-images.githubusercontent.com/76708409/111910778-b8ceef00-8a9d-11eb-9551-0de406768548.png)
![QQ图片20210321233033](https://user-images.githubusercontent.com/76708409/111910779-bbc9df80-8a9d-11eb-8ed2-3ce74fd9867c.jpg)

**Comment by q7871177xhj** [comment]
![QQ图片20210321234632](https://user-images.githubusercontent.com/76708409/111911282-e2891580-8a9f-11eb-9e65-66ef37a2da1e.png)

怎么折腾都没能成功 兑换零钱帐户的流量可以 兑换我的礼包里的(做任务领奖品) 1g流量日包就不行

**Comment by beer-on-ice** [comment]
![image](https://user-images.githubusercontent.com/25942344/111945462-bbb8f680-8b14-11eb-8319-f74eaddbb372.png)
一样激活失败

**Comment by Blender-S** [comment]
跟程序无关，今天我手动激活也一直不成功

**Comment by mixool** [comment]
有人提到过 是2个礼包的间隔太短  再试试呢

0 Failed. 18******153 1 Accomplished.
流量激活: 零钱账户 兑换成功 正在为您激活 1GB流量日包 我的礼包-流量包-1G日包-激活成功

**Comment by Blender-S** [comment]
还有一种可能，每月兑换次数超出阈值了！说激活不了的看看是不是兑换流量包超过35次以上了

**Comment by a1274989872** [comment]
> 导入参数liulactive @ w @ null @ 13800008888-13012341234 @ mygiftbag无法激活每日领取的1g流量包想问问是不是我引入错误了尝试
> 了好几个参数能够激活成功的还是以前的流量包代码的而每日领取的1g流量包激活没提示也没成功

可以留个qq吗？

**Comment by Blender-S** [comment]
已经确定激活数量达到阈值了
自己点击流量包进去看详情，点击激活失败旁边的问号即可看到
![Uploading IMG_20210325_201530.jpg…]()
