### ISSUE TITLE
发现检查更新的接口

### ISSUE THREAD

**Issue by chermy** [mixool/HiCnUnicom#42]
http://m.client.10010.com/mobileService/customer/getclientconfig.htm?version=android@7.0401
其实本质上就是个云控参数接口, 里面也包括检查更新功能. 输入一个老版本号时, 会显示出最新版本, 所以我们的签到脚本里面联通app的版本号是可以保持最新的. 
写法交给大家研究, 毕竟我只会写php😂

**Comment by mixool** [comment]
等个pr 
我估计得要放完假再弄

**Comment by mixool** [comment]
测了一下 http://m.client.10010.com/mobileService/customer/getclientconfig.htm?version=android@7.0201 这种不会返回版本
如果要只对某些版本返回的话 感觉也没啥必要更新
我觉得还是随缘手动改简单。。。
