### ISSUE TITLE
新活动 开年大庆

### ISSUE THREAD

**Issue by LxDebug** [mixool/HiCnUnicom#6]
![F586BC0D-B0EF-4586-9D93-D855BB3521D0](https://user-images.githubusercontent.com/27006147/103546463-fe880c80-4edd-11eb-8830-80a5a9b7e29b.png)
![EEBDC6B2-C65A-4A7E-8966-12445ED6D94D](https://user-images.githubusercontent.com/27006147/103546511-0e9fec00-4ede-11eb-926e-5a28282f315d.png)
看起来会持续一年，可以搞一搞嘛？

**Comment by mixool** [comment]
广西没看到这个活动
