### ISSUE TITLE
添加一个 Server酱  任务失败的通知吧

### ISSUE THREAD

**Issue by ipme** [mixool/HiCnUnicom#8]

**Comment by QiuYueBaiJXW** [comment]
基本不会失败 失败也没什么大的影响，一天运行两次，所以没有必要弄通知，天天发消息会很烦，我想大部分人都不想被打扰，如有需要可以自己添加

**Comment by mixool** [comment]
我也觉得没有必要通知, 如有PR，倒也是可以的

**Comment by mixool** [comment]
https://github.com/mixool/HiCnUnicom/commit/85c5a3bc3e5cfdb5b92c2c9db3409cc2539db1dd

写了个简单的TG通知，不传入参数就不执行
